### ISSUE TITLE
Fehler Seite 4 und Seite 6

### ISSUE THREAD

**Issue by 1177Julian** [Quantentheorie-1/Skriptum#1]
Auf Seite 6 ist ein Tippfehler unter dem Text zur Abbildung 3: "Trifft nun ein Photon auf einen gebundenes Elektron"

Auf Seite 4 sollte das n (glaube ich) nicht mit im x sein und auch nicht in 2.11 und 2.12

(Außerdem denke ich das x= e^-beta*h*w sein sollte, weil sonst in 2.11 mit dem 1/x nicht e^beta*h*w rauskommen kann, aber da bin ich mir nicht sicher)

**Comment by jakweiss** [comment]
Alle drei Fehler wurden ausgebessert und werden in Kürze in der Digitalversion aktualisiert werden.

Natürlich muss die Boltzmann-Verteilungsfunktion $P(E_{n}) = e^{\textcolor{red}{-}\beta E_{n}}$ entsprechen (wie in der kontinuierlichen Variante $P(E)$ in der Vertiefungsbox). Das Minus ist hier von integraler Bedeutung, da ansonsten z.B. die Normierbarkeit der Verteilung nicht mehr gegeben wäre.
Auch bei $x=e^{\beta \hbar \omega}$ müssen wir das $n$ weglassen um überhaupt die geometrische Summenformelanschreiben zu können. 

Vielen Dank für das aufmerksame Durchlesen und die Weitergabe der Fehler!
