### ISSUE TITLE
Formel 5.106 und 5.107

### ISSUE THREAD

**Issue by EL14Sg** [Quantentheorie-1/Skriptum#13]
Bei den Formeln 5.106 und 5.107 auf der Seite 93 wurde jeweils in der ersten Zeile das Quadrat (²) beim Erwartungswert von x bzw. p weggelassen. Im weiteren Verlauf des Umformens wurde es berücksichtigt, nur in der ersten Zeile fehlt es, soweit ich das beurteilen kann.

**Comment by jakweiss** [comment]
Super, danke, wurde ausgebessert! 💯
