### ISSUE TITLE
Fehler in Formel 6.110

### ISSUE THREAD

**Issue by sigl2000** [Quantentheorie-1/Skriptum#15]
Ich glaube in Formel 6.110 ist beim letzten Term in der ersten Zeile das Psi nach der Klammer zu viel, soweit ich das richtig verstehe, wurde das aber im vorherigen Schritt in die Klammer gezogen und wäre jetzt doppelt da.

**Comment by jakweiss** [comment]
Upps, natürlich, da hab ich wohl zuviel vom vorherigen Schritt mitgenommen, danke! 👍
