### ISSUE TITLE
Motivation: Spin

### ISSUE THREAD

**Issue by sigl2000** [Quantentheorie-1/Skriptum#16]
Auf Seite 144 im blauen Kästchen steht im dritten Absatz "Wäre das Elektron in einem 5s-Zustand (l=1) ...", aber hat ein Elektron im s-Zustand nicht immer die Quantenzahl l=0?

**Comment by simon-77** [comment]
Ja, da gehört "5p"-Zustand statt "5s", dann passt's auch mit dem Text zusammen.
