### ISSUE TITLE
Indexfehler S.151 Beispiel: Produkt der Pauli-Matrizen und Vektoroperatoren

### ISSUE THREAD

**Issue by AuTCerberus** [Quantentheorie-1/Skriptum#17]
Bei S.151 Beispiel: Produkt der Pauli-Matrizen und Vektoroperatoren ist nach 8.38 ein Indexfehler. δ_ik A_i B_j sollte δ_ij A_i B_j sein. 

![Bild_2023-01-12_094135130](https://user-images.githubusercontent.com/84043538/212018893-3552b7e2-9e21-4660-9c8b-716702a2b143.png)

**Comment by jakweiss** [comment]
Macht Sinn, wurde ausgebessert, danke fürs Bescheid geben. 🥇
