### ISSUE TITLE
1.3 Compton-Effekt: Trigonometrische Beziehung für den Kosinus-Term

### ISSUE THREAD

**Issue by Anophant** [Quantentheorie-1/Skriptum#27]
Zwischen Gleichung 1.33 & 1.34 wurde die Kosinus-Beziehung 1-cos(v)=2*sin^2(v/2) bzw. 1-cos(v)=1/2*sin^2(v/2) einmal mit einem falschen Vorfaktor angeschrieben

**Comment by jakweiss** [comment]
Super, danke fürs Bescheid geben!
Wurde ausgebessert, in der neuen Version des Skriptums sollte es dann passen.
