### ISSUE TITLE
Temperaturen Abb 2. Seite 4

### ISSUE THREAD

**Issue by KMatzi** [Quantentheorie-1/Skriptum#3]
Kann es sein, dass bei Abbildung 2 (links) auf Seite 4 die Temperaturen falsch aufgetragen wurden? Intuitiv würde ich vermuten, dass die Emergiedichte mit steigender Temperatur wächst und nicht wie in der Abbildung sinkt.

**Comment by jakweiss** [comment]
Stimmt natürlich, mit zunehmender Temperatur sollte sich die maximale Frequenz $\omega_{\text{max}}$ zu immer größeren Frequenzen $\omega$ verschieben, beziehunsgsweise die Fläche unter $\varepsilon(\omega)$ zunehmenden. Die Reihenfolge der Labels war vertauscht, wurde soeben ausgebessert. Danke!
