### ISSUE TITLE
Vertauschung von $` \phi `$ und  $`| \phi |^2 `$ bzw. $` Re(\varphi) `$ und $` 2 Re(\varphi) `$ auf Seiten 24-26

### ISSUE THREAD

**Issue by sgradauer** [Quantentheorie-1/Skriptum#32]
Auf Seite 24 wird $` \varphi(x, t) `$ als der Exponent der Wellenfunktion $` \phi(x, t) `$ definiert:

```math
\phi(x, t) =: N e^{ \varphi(x,t) }
```

Damit ist das Betragsquadrat der WF:

```math
|\phi|^2 = N N^*  e^{ \varphi} e^{ \varphi^*} = |N|^2 e^{ \varphi + \varphi^*}= |N|^2 e^{ 2Re(\varphi) } 
```
Damit ist der Exponent der WF  das doppelte des Realteils der $´ \varphi ´$-Funktion (also $´ 2 Re( \varphi ) ´$)

Auf Seite 25 wird jedoch nicht $`Re(\varphi)`$ berechnet, sondern das doppelte. In der vorletzten Zeile des vorletzten Formelblocks auf Seite 24 steht die Definition von $`\varphi`$ als Exponent, während in der ersten Zeile des ersten Formelblocks auf Seite 25 das doppelte davon eingesetzt wurde. Die Folge diese Fehlers zieht sich bis zum Ende der subsubsection auf seite 26.

Im Folgenden wird  noch einmal  der Betrag der Wellenfunktion mit dem Betragsquadrat der Wellenfunktion verwechselt, nämlich in der Bildunterschrift von Abb. 6 auf Seite 26:

> Darstellung des Realteils eines Wellenpakets [...], wobei die Einhüllende das Absolutquadrat $`|\phi(x, t)|^2`$ ist.

Die Einüllende ist allerdings selbstverständlich nur der Betrag der WF und nicht das Betragsquadrat.

**Comment by HelmutHoerner** [comment]
Ich überarbeite gerade das Kapitel "Wellenpaket", und habe jedenfalls im Zuge der Überarbeitung schon mal den 2 RE(phi) - Fehler behoben.

**Comment by HelmutHoerner** [comment]
Caption von Abb. 6 wurde geändert.

**Comment by sgradauer** [comment]
Vielen Dank!
