### ISSUE TITLE
Falsche Herleitung und Ergebnis von Phasengeschwindigkeit auf Seite 11

### ISSUE THREAD

**Issue by sgradauer** [Quantentheorie-1/Skriptum#33]
Auf Seite 11 wird versucht, die Phasen sowie Gruppengeschwindikeiten einer Materiewelle herzuleiten. Dafür wird allerdings fälschlicherweise $` E = m v²/2 `$ angenommen, was die Ruhemasse vernachlässigt. Folglich wird ein falsches Ergebnis für die Phasengeschwindigkeit erhalten:

```math
v_{Ph} = \frac{\hbar k}{2m}

\qquad

v_{G} = \frac{\hbar k}{m}

```

Damit wäre die Phasengeschwindigkeit immer die Hälfte der Gruppengeschwindigkeit, tatsächlich ist die Phasengeschwindigkeit aber immer höher als die Lichtgeschwindigkeit (für $` m > 0 `$).

Richtig ist aber:
```math
v_{Ph} = \frac{\omega}{k} = \frac{\hbar \omega}{\hbar k} = \frac{E}{p} = \frac{\gamma m c^2}{\gamma m v} = \frac{c^2}{v} = \frac{c^2}{\frac{p}{\gamma m}} =\frac{c^2}{\frac{\hbar k}{\gamma m}}   \approx \frac{c^2 m}{\hbar k}
```
[6.5 Phasengeschwindigkeit und Brechung von Materiewellen, ETH Zürich](https://qudev.phys.ethz.ch/static/content/science/BuchPhysikIV/PhysikIVch6.html#x36-860006.5)
[Phasengeschwindigkeit, Materiewelle, Wikipedia](https://de.wikipedia.org/wiki/Phasengeschwindigkeit#Materiewelle)

Die Herleitung der Gruppengeschwindigkeit ist außerdem ein bissl ein Zirkelschluss, dafür genügt eigentlich folgender Zweizeiler:

```math
\hbar \mathbf{k} = \mathbf{p} = mv_G
```
```math
\mathbf{v_G} = \frac{\hbar \mathbf{k}}{m} 
```

**Comment by HelmutHoerner** [comment]
Das die Phasengeschwindigkeit und Gruppengeschwindigkeit nur im nicht-relativistischen Grenzfall so stimmt, ist natürlich richtig. Das ist für die "Schrödinger"-Quantenphysik ausreichend, weil die ja auch nicht-relativistisch ist. Ich habe den Text im Skriptum jedenfalls jetzt so erweitert, dass darauf hingewiesen wird, dass das nur bei v << c gilt. 
Ad "Zirkelschluss": Ja, eh, kann man so sehen; aber es ist ja auch schön, zu sehen, dass alles passt, wenn man die Definition verwendet.

**Comment by sgradauer** [comment]
Aber das Problem liegt ja gerade im nichtrelativistischen Grenzfall, wo $` v_Ph `$ gegen unendlich geht, laut Skriptum jedoch gegen 0.

**Comment by HelmutHoerner** [comment]
Faszinierend. Das muss ich mir näher ansehen.

Sie haben auf den ersten Blick Recht; in Wikipedia und anderen Quellen wird das so hergeleitet wie Sie das vorschlagen.

Gleichzeitig findet man z.B. in diesem Skriptum https://www.wmi.badw.de/fileadmin/WMI/Lecturenotes/Physics_3/Gross_Physik_III_Kap_12.pdf
auf PDF-Seite  21  (gedruckte Seite 469) folgende widersprüchliche Angabe:

Im Text steht zunächst, dass “die Phasengeschwindigkeit einer Materiewelle immer größer als die Lichtgeschwindigkeit ist.” 

In der zugehörigen Fußnote steht dann aber unter der Überschrift “nicht-relativistisches Teilchen”:
”Es gilt v_ph = ... = \hbar k / (2m)”

Ich werde das recherchieren.

mfG
Helmut Hörner

**Comment by sgradauer** [comment]
Was mir auch noch grade eingefallen ist: bei der Skriptums Formel geht für den Grenzfall $ m=0 $
, z.B. bei Licht, die Pasengeschwindigkeit gegen unendlich anstatt gegen c, während die Formel von ETH bzw. Wiki mit gegen c geht.

Auch interessant ist, dass auf der ETH Seite ein Beispiel für die Brechung eines Elektrons an einer Potentialstufe untersucht wird. Dies erlaubt es, die ETH Formel mit dem Experiment oder der Klassischen Brechung eines Elektrons zu verifizieren.

Vielen Dank jedenfalls für das Skript, dass Sie es online verfügbar machen und sich um Verbesserungsvorschläge kümmern.

LG, Stefan Gradauer
-------- Original-Nachricht --------
Am 24. Okt. 2023, 22:24, schrieb HelmutHoerner :

**Comment by HelmutHoerner** [comment]
Nach Diskussion mit meinen Kollegen und Prof. Rotter, sowie weiterer Recherche, was man so in den Lehrbüchern findet, kann ich zu der Frage vorerst einmal wie folgt Stellung nehmen: 

- Man findet durchaus “beide Varianten” der Phasengeschwindigkeit in den Lehrbüchern (auch die  Variante unseres Skriptums z.B.  in Claude Cohen-Tannoudij “Quantenmechanik 1” und vielen anderen).

- Um die Variante v_ph = c²/v_g zu erhalten, muss man annehmen, dass die Energie eines Teilchens der relativistischen Beziehung entspricht; also auch ein ruhendes Teilchen hat schon mal E=m_0*c² Energie (sehr, sehr viel)

- Das passt eigentlich nicht so recht zur Schrödingergleichung, die eindeutig nicht-relativistisch ist. In der “klassisch-nicht-relativistischen” Sicht hat ein freies Teilchen einfach nur die kinetische Energie p²/(2m), und nicht mehr. Ein ruhendes freies Teilchen hat gar keine Energie.

- Wen man das voraussetzt, kommt man zur  Dispersionsrelation unseres Skriptums. Sie passt wunderbar im Rahmen des Modells.

- Wenn man dennoch auf die relativistische Energie (und den relativistischen Impuls) besteht, sollte man mindestens die Klein-Gordon-Gleichung (besser Dirac-Gleichung) nehmen, und dann erhält man die v_ph = c²/v_g Beziehung.

- Was ist jetzt “richtig”? Direkt beobachtbar ist die Phasengeschwindigkeit nicht. Ob das Gedankenexperiment mit der Elektronenbeugung wirklich geeignet ist, die “superluminale” Variante zu beweisen, wird hier bei uns noch mit geteilter Meinung diskutiert.  

- Im Rahmen des Modells der Schrödingergleichung scheint es jedenfalls sehr plausibel, als Energie nur die nicht-relativistische kinetische Energie einzusetzen.

- Fazit: Wir nehmen vorerst diesbezüglich keine Änderung im Skriptum vor.

L.G.,
Helmut Hörner

PS: Dass bei der Skriptums-Formel für m=0 die Phasengeschwindigkeit gegen unendlich geht, scheint mir kein Problem zu sein, weil (1) wir ja eben nur nicht-relativistische Fälle betrachten, und (2) die Phasengeschwindigkeit ja prinzipiell größer als c sein darf.
