### ISSUE TITLE
Fehler in Formel (3.30)

### ISSUE THREAD

**Issue by bluePlatinum** [Quantentheorie-1/Skriptum#5]
Ich glaube, dass in Formel (3.30) ein \tilde{\psi} nach dem V(r) fehlt. Es müsste ja nach der Separation sowohl auf V(r) als auch auf E multipliziert werden.

**Comment by jakweiss** [comment]
Vollkommen richtig, wenn der sollständige Hamiltonoperator $\hat{H}$ (kinetischer und potentieller Energieterm) auf eine Wellenfunktion $\psi(\mathbf{r})$ wirkt, müssen auch tatsächlich die individuellen Terme $\psi(\mathbf{r})$ beeinflussen:
$$\left( -\frac{\hbar^{2}}{2m} \Delta + V(\mathbf{r}) \right) \psi(\mathbf{r}) = -\frac{\hbar^{2}}{2m} \Delta \psi(\mathbf{r}) + V(\mathbf{r}) \psi(\mathbf{r}) $$
Danke fürs Bescheid geben!
