### ISSUE TITLE
Seite 16 im Text vor Gleichung 3.29 

### ISSUE THREAD

**Issue by baestis** [Quantentheorie-1/Skriptum#6]
_Es gilt $E=\hbar \omega$ beziehungsweise $\underline{\omega=\hbar / E}$ ..._
 
sollte doch 

_Es gilt $E=\hbar \omega$ beziehungsweise $\underline{\omega=E / \hbar}$ ..._

sein?

**Comment by jakweiss** [comment]
Selbstverständlich sollte das so sein, wurde soeben ausgebessert. Danke!
