### ISSUE TITLE
Fehler in Glg. 3.43, 3.46 und 3.48

### ISSUE THREAD

**Issue by sigl2000** [Quantentheorie-1/Skriptum#7]
In Gleichung 3.43 steht sigma_k  = 1/(2*d) allerdings wird in 3.38 eine Gaußfunktion definiert in deren Exponent d^2 statt 1/(2*sigma^2) steht. Somit müsste doch eigentlich (sigma_k)^2 = 1/(2*(d^2)) sein? Weiters wird hier sigma_x proportional zu d^2 angeschrieben, obwohl es sich doch eigentlich nur um eine Proportionalität zu d handeln sollte, wenn man diese Gleichung mit 3.41 (der allg. Gaußfunktion) vergleicht.
In Gleichung 3.46 ist ein Tippfehler da im rotgeschriebenen Term die Standardabweichung mit dem Index 2 versehen ist, obwohl es sich wahrscheinlich um ein Quadrat handeln sollte.
In Gleichung 3.48 wird derselbe Trick wie in Gleichung 3.46 angewendet, allerdings ist in der Gleichung beim Einsetzen dieses Tricks auf die Gleichung 3.48 (also auf sich selbst) verwiesen.

**Comment by jakweiss** [comment]
Danke für die Bemerkungen, Tipp- und Verweisfehler wurden ausgebessert und werden in der neuen Version dann passen.

Zur ersten Frage: An dieser Stelle muss man aufpassen, beziehungsweise wurde im Skriptum nicht klar genug formuliert. Die Normalverteilung ist definiert als:
$$N(x;\mu_{0},\sigma^{2}) = \frac{1}{\sqrt{2 \pi} \sigma}e^{ \frac{-(x-\mu_{0})^{2}}{2 \sigma^{2}}}$$  
Als Funktion gibt sie eine _Wahrscheinlichkeitsdichte_ wieder. Erinnern wir uns an die Interpretation von Wellenfunktionen $\psi(x)$, wissen wir, dass erst das Betragsquadrat von $\vert \psi(x) \vert^{2}$ als eine _Wahrscheinlichkeitsdichte_ interpretiert werden kann (während $\psi(x)$ nicht direkt bestimmt werden kann). Betrachten wir daher $\vert \phi(x)\vert^{2}$ aus Gl. (3.42) gilt:
$$\vert \phi(x,t) \vert^{2} = \frac{1}{\sqrt{2 \pi d^{2} [1 + \Delta^{2}(t)]}} e^{ \frac{-(x - v_{0} t)^{2}}{2 d^{2} [1 + \Delta^{2}(t)]}} \Longrightarrow N(x;\mu_{0},\sigma^{2})$$ 
Der Vergleich beider Wahrscheinlichkeitsdichten erlaubt die Zuordnung des Erwartungswert $\mu=v_{0}t$ und der Standardabweichung $\sigma=d \sqrt{1 + \Delta^{2}(t)}$. Die Wellenfunktion im $k$-Raum in Gl. (3.40) ist allerdings auch genau das: eine _Wellenfunktion_ und _keine Wahrscheinlichkeitsdichte_. Erst die Bildung des Betragsquadrates erlaubt wieder den Vergleich mit der Normalverteilung:
$$\vert \overline{\psi}(k) \vert^{2} = \Big\vert A e^{-(k-k_{0})^{2}d^{2}} \Big\vert^{2} = \vert A \vert^{2} e^{-2(k-k_{0})^{2}d^{2}} \Longrightarrow N(x;\mu_{0},\sigma^{2})$$ 
Jetzt passt dann auch die im Skriptum schlecht motivierte Relation:
$$e^{-2(k-k_{0})^{2}d^{2}} = e^{ \frac{-(k-\mu_{0})^{2}}{2 \sigma^{2}}} \textcolor{blue}{\Longrightarrow} \mu_{0} = k_{0} \quad\textcolor{blue}{\text{und}}\quad \frac{1}{2\sigma^{2}} = 2d^{2} \Longleftrightarrow \sigma^{2} = \frac{1}{4d^{2}}$$

**Comment by sigl2000** [comment]
Danke für die Aufklärung. So gesehen ergibt das ganze natürlich Sinn.
