### ISSUE TITLE
Seite 19: Klammerfehler - Beispielbox

### ISSUE THREAD

**Issue by simon-77** [Quantentheorie-1/Skriptum#8]
Auf Seite 19 in der Beispiel-Box "Keine Normerhaltung mit komplexem Potential" passen die Klammern in der 4. Formelzeile nicht.

Eine der "auf"-Klammern ist zu viel und dann sollten die gleichen Klammer-Typen auf und wieder zu gemacht werden.

**Comment by jakweiss** [comment]
Super danke, wurde ausgebessert.
